# General configurations

# Public base URL where EDDIE tariff information framework is hosted and accessible by external clients
eddie.public.url=http://localhost:${server.port:8080}

# Data source specific configurations

# AT E-Control data source
data-source.at.e-control.enabled=false
#data-source.at.e-control.base-url=REPLACE_ME
#data-source.at.e-control.username=REPLACE_ME
#data-source.at.e-control.password=REPLACE_ME
